DanceStudioManager/Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DanceStudioManager
{
    public class Instructor
    {
        public int Id { get; set; }
        [Required]
        public string Firstname { get; set; }
        [Required]
        public string Lastname { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public bool SendEmail { get; set; }
        public string Gender { get; set; }
        public int StudioId { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string DateOfBirthToString { get; set; }
        [Required]
        public int procentOfProfit { get; set; }
    }
}

DanceStudioManager/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DanceStudioManager
{
    [Authorize]
    public class ReportsController : Controller
    {
        private readonly ClassDataAccess _classDataAccess;
        private readonly StudentsDataAccess _studentDataAccess;
        private readonly AttendanceDataAccess _attendanceDataAccess;
        private readonly InstructorDataAccess _instructorDataAccess;
        private readonly UserDataAccess _userDataAccess;
        private readonly StudioDataAccess _studioDataAccess;

        public ReportsController(ClassDataAccess classDataAccess, StudentsDataAccess studentDataAccess, AttendanceDataAccess attendanceDataAccess,
            InstructorDataAccess instructorDataAccess, UserDataAccess userDataAccess, StudioDataAccess studioDataAccess)
        {
            _classDataAccess = classDataAccess;
            _studentDataAccess = studentDataAccess;
            _attendanceDataAccess = attendanceDataAccess;
            _instructorDataAccess = instructorDataAccess;
            _userDataAccess = userDataAccess;
            _studioDataAccess = studioDataAccess;
        }
        public IActionResult ClassStudent()
        {
            ViewBag.text = "Class-Student report";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            return View("Views/Studio/ClassStudentReport.cshtml");
        }

        public IActionResult SearchStudent(string genre, string level, string type)
        {
            var students = new List<ClassStudentVM>();
            var classes = new List<Class>();

            if (genre != null && level != null && type != null)
            {
                classes = _classDataAccess.SearchClass(genre, level, type, GetCurrentStudioId());
            }
            else
            {
                classes = _classDataAccess.GetAllClasses(GetCurrentStudioId());
            } 

            foreach (var _class in classes)
            {
                foreach (var id in _classDataAccess.GetStudentsConnectedToClass(_class.Id, GetCurrentStudioId()))
                {
                    var s = _studentDataAccess.GetStudentById(id);
                    ClassStudentVM student = new ClassStudentVM();

                    student.Firstname = s.Firstname;
                    student.Lastname = s.Lastname;
                    student.Email = s.Email;
                    student.Genre = _class.Genre;
                    student.Level = _class.Level;
                    students.Add(student);
                }
            }
            return Json(students);
        }

        public IActionResult Profit(string classError)
        {
            ViewBag.text = "Profit report";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            if (classError != null) ViewBag.classError = classError;
            return View("Views/Studio/ProfitReport.cshtml");
        }

        public IActionResult SearchProfitForPeriod(DateTime dateFrom, DateTime dateTo, string classGenre, string level, string type)
        {
            List<Profit> finalProfit = new List<Profit>();
            var _class = new List<Class>();
            DateTime defaultDatetime = default(DateTime);
            var firstDayOfMonth = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);

            if (dateFrom != defaultDatetime && dateTo != defaultDatetime || classGenre != null || level != null)
            {
                _class = _classDataAccess.SearchClass(classGenre, level, type, GetCurrentStudioId());
            }
            else
            {
                _class = _classDataAccess.GetAllClasses(GetCurrentStudioId());
                dateFrom = firstDayOfMonth;
                dateTo = DateTime.Now.Date;
            }
            if (_class.Count > 0)
            {
                foreach (var c in _class)
                {
                    Profit profit = new Profit();
                    var attendances = _attendanceDataAccess.SearchAttendancesByClassId(c.Id);

                    profit.ProfitForPeriod = 0;
                    profit.NumberOfStudents = 0;
                    profit.Attendances = 0;
                    profit.Level = c.Level;
                    profit.ClassGenre = c.Genre;
                    profit.Type = c.ClassType;
                    profit.DateFrom = dateFrom.ToString("MM-dd-yyyy");
                    profit.DateTo = dateTo.ToString("MM-dd-yyyy");

                    for (DateTime date = dateFrom; date <= dateTo; date = date.AddDays(1))
                    {
                        foreach (var at in attendances)
                        {
                            double sum = 0;
                            var numberOfStudents = 0;

                            if (at.Date == date)
                            {
                                double instructorPay = 0;
                                double procent = 0;

                                numberOfStudents += _classDataAccess.GetStudentsConnectedToClass(at.ClassId, GetCurrentStudioId()).Count;
                                foreach (var i in _classDataAccess.GetInstructorsConnectedToClass(at.ClassId, GetCurrentStudioId()))
                                {
                                    var instructor = _instructorDataAccess.GetInstructorById(i);
                                    procent += instructor.procentOfProfit;
                                }

                                sum = numberOfStudents * (_classDataAccess.SearchClass(at.ClassId, GetCurrentStudioId()).PricePerHour);
                                instructorPay = sum * (procent / 100);
                                sum = sum - instructorPay;
                                profit.Attendances++;
                            }
                            profit.ProfitForPeriod += Math.Round(sum);
                        }
                    }
                    profit.NumberOfStudents = _classDataAccess.GetStudentsConnectedToClass(c.Id, GetCurrentStudioId()).Count;
                    finalProfit.Add(profit);
                }
            }
            else
            {
                string classError = "A class with this genre, level or type does not exists!";
                return RedirectToAction("Profit", new { classError });
            }

            return Json(finalProfit);
        }

        private int GetCurrentStudioId()
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);
            var studioId = _userDataAccess.GetUserById(userId).StudioId;

            return studioId;
        }
    }
}

DanceStudioManager/Controllers/StudioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Security.Claims;

namespace DanceStudioManager
{
    [Authorize]
    public class StudioController : Controller
    {
        private readonly StudentsDataAccess _studentDataAccess;
        private readonly StudioDataAccess _studioDataAccess;
        private readonly InstructorDataAccess _instructorDataAccess;
        private readonly ClassDataAccess _classDataAccess;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly UserDataAccess _userDataAccess;
        private readonly AttendanceDataAccess _attendanceDataAccess;
        private readonly CalendarHelp _calendarHelp;

        public StudioController(StudentsDataAccess studentDataAccess, StudioDataAccess studioDataAccess, InstructorDataAccess instructorDataAccess,
            ClassDataAccess classDataAccess, IHttpContextAccessor httpContextAccessor, UserDataAccess userDataAccess, AttendanceDataAccess attendanceDataAccess,
            CalendarHelp calendarHelp)
        {
            _studentDataAccess = studentDataAccess;
            _studioDataAccess = studioDataAccess;
            _instructorDataAccess = instructorDataAccess;
            _classDataAccess = classDataAccess;
            _httpContextAccessor = httpContextAccessor;
            _userDataAccess = userDataAccess;
            _attendanceDataAccess = attendanceDataAccess;
            _calendarHelp = calendarHelp;
        }
        public IActionResult Dashboard()
        {
            ViewBag.text = "Dashboard";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            DashboardNeeds dashboardNeeds = new DashboardNeeds();
            var allClasses = _classDataAccess.GetAllClasses(GetCurrentStudioId());
            var allStudents = _studentDataAccess.GetAllStudents(GetCurrentStudioId());
            var allInstructors = _instructorDataAccess.GetAllInstructors(GetCurrentStudioId());

            foreach (var _class in allClasses)
            {
                var classShedule = _classDataAccess.GetClassShedule(_class.Id);
                foreach (var s in classShedule)
                {
                    if (s.Day == DateTime.Now.DayOfWeek.ToString() && _class.StartDay <= DateTime.Now)
                    {
                        _class.Hour = s.Hour;
                        dashboardNeeds.classesForToday.Add(_class);
                    }
                }
            }

            foreach (var st in allStudents)
            {
                var sL = new SelectListItem()
                {
                    Value = st.Id.ToString(),
                    Text = $"{st.Firstname} {st.Lastname}"
                };

                dashboardNeeds.AllStudents.Add(sL);
            }

            foreach (var ins in allInstructors)
            {
                var iL = new SelectListItem()
                {
                    Value = ins.Id.ToString(),
                    Text = $"{ins.Firstname} {ins.Lastname}"
                };

                dashboardNeeds.AllInstructors.Add(iL);
            }
            return View(dashboardNeeds);
        }

        [HttpPost]
        public IActionResult Dashboard(int classId)
        {
            ClassStudentVM dashboardNeeds = new ClassStudentVM();
            var instructorList = _classDataAccess.GetInstructorsConnectedToClass(classId, GetCurrentStudioId());
            var studentsIdList = _classDataAccess.GetStudentsConnectedToClass(classId, GetCurrentStudioId());
            var _class = _classDataAccess.SearchClass(classId, GetCurrentStudioId());
           
            foreach (var idsIns in instructorList)
            {
                var instructor = _instructorDataAccess.GetInstructorById(idsIns);
                dashboardNeeds.InstructorsList.Add(instructor);
            }

            foreach (var idsStu in studentsIdList)
            {
                var student = _studentDataAccess.GetStudentById(idsStu);
                dashboardNeeds.StudentsList.Add(student);
            }

            dashboardNeeds.PricePerHour = _class.PricePerHour;
            dashboardNeeds.Level = _class.Level;
            dashboardNeeds.ClassId = classId;
            var shedule  = _classDataAccess.GetClassShedule(classId);

            foreach(var s in shedule)
            {
                dashboardNeeds.SheduleDays.Add($" {s.Day} - {s.Hour} ");
            }

            return Json(dashboardNeeds);
        }

        public IActionResult Students()
        {
            ViewBag.text = "Students";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            return View();
        }

        public IActionResult GetStudents(string firstname, string lastname, string email)
        {
            List<Student> studentList = new List<Student>();
            Student student = new Student();

            if ((string.IsNullOrEmpty(firstname) || firstname == "null") 
                && (string.IsNullOrEmpty(lastname) || lastname == "null") 
                && (string.IsNullOrEmpty(email) || email == "null"))
            {
                studentList = _studentDataAccess.GetAllStudents(GetCurrentStudioId());
            }
            else
            {
                student.Firstname = firstname;
                student.Lastname = lastname;
                student.Email = email;
                studentList = _studentDataAccess.SearchStudents(student);
            }

            return Json(studentList);
        }

        public IActionResult AddNewStudent(Student student)
        {
            int studioId = GetCurrentStudioId();

            student.DateOfBirth = DateTime.ParseExact(student.DateOfBirthToString, "MM/dd/yyyy", CultureInfo.InvariantCulture);

            _studentDataAccess.AddNewStudent(student, studioId);
            return RedirectToAction("Students");
        }

        public void EditStudent(Student student)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _studentDataAccess.UpdateStudent(student, userId);
        }

        /// <summary>
        /// Students page.
        /// </summary>
        /// <param name="student"></param>
        public void DeleteStudent(Student student)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _studentDataAccess.DeleteStudent(student, userId);
        }

        /// <summary>
        /// Edit class modal.
        /// </summary>
        /// <param name="id"></param>
        [HttpPost]
        public void DeleteStudentFromClass(int id, int classid)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _studentDataAccess.DeleteStudentFromClass(id, classid, userId);
        }

        public IActionResult Instructor()
        {
            ViewBag.text = "Instructors";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            return View();
        }

        public IActionResult GetInstructor(string firstname, string lastname, string email)
        {
            List<Instructor> instructorList = new List<Instructor>();
            Instructor instructor = new Instructor();

            if ((string.IsNullOrEmpty(firstname) || firstname == "null")
                && (string.IsNullOrEmpty(lastname) || lastname == "null")
                && (string.IsNullOrEmpty(email) || email == "null"))
            {
                instructorList = _instructorDataAccess.GetAllInstructors(GetCurrentStudioId());
            }
            else
            {
                instructor.Firstname = firstname;
                instructor.Lastname = lastname;
                instructor.Email = email;
                instructorList = _instructorDataAccess.SearchInstructors(instructor);
            }

            return Json(instructorList);
        }

        public IActionResult AddNewInstructor(Instructor instructor)
        {
            instructor.DateOfBirth = DateTime.ParseExact(instructor.DateOfBirthToString, "MM/dd/yyyy", CultureInfo.InvariantCulture);

            int studioId = GetCurrentStudioId();
            _instructorDataAccess.AddNewInstructor(instructor, studioId);
            return RedirectToAction("Instructor");
        }

        public void EditInstructor(Instructor instructor)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _instructorDataAccess.UpdateInstructor(instructor, userId);
        }
        
        /// <summary>
        /// Instructor page.
        /// </summary>
        /// <param name="instructor"></param>
        public void DeleteInstructor(Instructor instructor)
        {

DanceStudioManager/Views/Studio/ClassStudentReport.cshtml
@{
    ViewData["Title"] = "ClassStudentReport";
    Layout = "_LayoutStudio";
}

@model Class

<link href="~/css/Reports.css" rel="stylesheet" />
<link href="~/css/ThemeJQueryGrid/jquery-ui.min.css" rel="stylesheet" />
<link href="~/css/ui.jqgrid.css" rel="stylesheet" />

<form id="formClassStudentReport" method="post" class="mediumForm">
    <div class="card-body">
        <div class="form-row mb-2">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="Genre">Class genre: </label>
                    <input asp-for="Genre" type="text" class="form-control form-control-plaintext w-75" id="Genre" placeholder="Genre">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="Level">Class level: </label>
                    <input asp-for="Level" type="text" class="form-control form-control-plaintext w-75" id="Level" placeholder="Level">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="ClassType">ClassType: </label>
                    <input asp-for="ClassType" type="text" class="form-control form-control-plaintext w-75" id="ClassType" placeholder="ClassType">
                </div>
            </div>
        </div>
        <div class="form-row mb-3">
            <button asp-controller="Reports" asp-action="SearchStudents" type="submit" id="SearchStudentsForClass" class="btn btn-secondary w-25 h-25 mt-4">Search students</button>
        </div>
        <table id="jqGrid"></table>
        <div id="jqGridPager"></div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/jqGrid/grid.locale-en.js"></script>
    <script src="~/js/jqGrid/jquery.jqGrid.js"></script>
    <script src="~/js/ClassStudentReport.js"></script>
}

DanceStudioManager/Views/Studio/Classes.cshtml
@{
    ViewData["Title"] = "Classes";
    Layout = "_LayoutStudio";
}

@model ClassStudentVM

<link href="~/css/ThemeJQueryGrid/jquery-ui.min.css" rel="stylesheet" />
<link href="~/css/ui.jqgrid.css" rel="stylesheet" />
<link href="~/css/Class.css" rel="stylesheet" />

<form id="formClasses" method="post" class="mediumForm">
    <div class="card-body">
        <div class="form-row mb-2">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="Genre">Genre: </label>
                    <input asp-for="Genre" type="text" class="form-control form-control-plaintext w-75" id="Genre" placeholder="Genre">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="Level">Level: </label>
                    <input asp-for="Level" type="text" class="form-control form-control-plaintext w-75" id="Level" placeholder="Level">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="ClassType">ClassType: </label>
                    <input asp-for="ClassType" type="text" class="form-control form-control-plaintext w-75" id="ClassType" placeholder="ClassType">
                </div>
            </div>
        </div>
        <div id="success" style="color:red"></div>
        <div class="form-row">
            <button type="submit" id="SearchClasses" class="btn btn-secondary w-25 h-25 mt-4">Search class</button>
            <button type="button" id="addNew" class="btn btn-secondary w-25 h-25 mt-4 ml-3" data-toggle="modal" data-target="#classesModal">Add New</button>
        </div>
        <label id="classError">@ViewBag.classError</label>
        <table id="jqGrid"></table>
        <div id="jqGridPager"></div>
    </div>
</form>


<!-- Modal -->
<form method="post" asp-controller="Studio" asp-action="AddNewClass">
    <div class="modal fade " id="classesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title ml-5 mt-4" id="exampleModalLabel">Add new class</h5>
                    <img src="~/Pictures/danceClass.jpg" alt="danceClass" class="ml-4" width="70" height="70" />
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input asp-for="Genre" type="text" class="modal-input " id="Genre" placeholder="Genre">
                    <select asp-for="Level" class="browser-default custom-select modal-input" name="Level">
                        <option value="" selected>Level</option>
                        <option value="beginners">beginners</option>
                        <option value="intermidiate">intermidiate</option>
                        <option value="veterans">veterans</option>
                        <option value="professionals">professionals</option>
                    </select>
                    <input asp-for="PricePerHour" type="number" class="modal-input " id="PricePerHour" placeholder="PricePerHour" value="">
                    <select asp-for="ClassType" class="browser-default custom-select modal-input" name="ClassType">
                        <option value="" selected>Class Type</option>
                        <option value="private">private</option>
                        <option value="group">group</option>
                    </select>
                    <h6 class="label label-default">Select shedule Days</h6>
                    <select asp-for="SheduleDays" class="modal-input h-auto SheduleDays" multiple="multiple" name="SheduleDays[]">
                        <option value="Monday">Monday</option>
                        <option value="Tuesday">Tuesday</option>
                        <option value="Wednesday">Wednesday</option>
                        <option value="Thursday">Thursday</option>
                        <option value="Friday">Friday</option>
                        <option value="Saturday">Saturday</option>
                        <option value="Sunday">Sunday</option>
                    </select>

                    <input asp-for="Hour" type="text" class="modal-input " id="Hour" placeholder="Hour" value="">

                    <h6 class="label label-default">Select students </h6>
                    <select asp-for="Students" asp-items="@Model.Students" class="modal-input h-auto Students" multiple="multiple" name="StudentsIds[]"></select>

                    <h6 class="label label-default">Select instructor/s</h6>
                    <select asp-for="Instructors" asp-items="@Model.Instructors" class="modal-input h-auto Instructors" multiple="multiple" name="InstructorsIds[]"></select>

                    <input asp-for="StartDayToString" type="text" class="datepicker modal-input" id="StartDayToString" placeholder="Start Day">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Modal Update class -->
<form method="post" asp-controller="Studio" id="EditModalForm" asp-action="UpdateClass">
    <div class="modal fade " id="EditClassModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title ml-5 mt-4" id="exampleModalLabel">Edit class </h5>
                    <img src="~/Pictures/danceClass.jpg" alt="danceClass" class="ml-4" width="70" height="70" />
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <h5 class="modal-title mt-4" id="exampleModalLabel">Class info</h5>
                <div class="modal-body">
                    <h6>Students</h6>
                    <div class="table-wrapper-scroll-y border-top border-bottom">
                        <table class="table table-responsive-sm table-borderless" id="StudentsTable"></table>
                    </div>
                    <h6 class="m-3">Instructor/s</h6>
                    <div class="table-wrapper-scroll-y border-top border-bottom">
                        <table class="table table-responsive-sm table-borderless" id="InstructorTable"></table>
                    </div>
                    <div class="m-2 border-bottom">
                        <h6>Price per hour - <a id="price"></a></h6>
                        <h6>Level - <a id="level"></a></h6>
                        <h6>Shedule - <a id="Shedule"></a></h6>
                    </div>
                    <div class="m-3">
                        <a> Change price per hour</a>
                        <input asp-for="PricePerHour" type="number" class="modal-input " id="PricePerHour" value="@Model.PricePerHour">

                        <a> Change level</a>
                        <select class="browser-default custom-select modal-input" name="Level">
                            <option value="" selected>Level</option>
                            <option value="beginners">beginners</option>
                            <option value="intermidiate">intermidiate</option>
                            <option value="veterans">veterans</option>
                            <option value="professionals">professionals</option>
                        </select>

                        <a> Change Shedule hour</a>
                        <input asp-for="Hour" type="text" class="modal-input " id="hour">

                        <h6 class="label label-default">Change Shedule Days</h6>
                        <select asp-for="SheduleDays" class="modal-input h-auto SheduleDays" multiple="multiple" name="SheduleDays[]">
                            <option value="Monday">Monday</option>
                            <option value="Tuesday">Tuesday</option>
                            <option value="Wednesday">Wednesday</option>
                            <option value="Thursday">Thursday</option>
                            <option value="Friday">Friday</option>
                            <option value="Saturday">Saturday</option>
                            <option value="Sunday">Sunday</option>
                        </select>

                        <a>Add students </a>
                        <select asp-for="Students" asp-items="@Model.Students" class="modal-input h-auto Students" multiple="multiple" name="StudentsIds[]"></select>

                        <a>Add instructor/s</a>
                        <select asp-for="Instructors" asp-items="@Model.Instructors" class="modal-input h-auto Instructors" multiple="multiple" name="InstructorsIds[]"></select>
                        <input type="hidden" asp-for="ClassId" class="modal-input " id="ClassId">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" id="bSave" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/jqGrid/grid.locale-en.js"></script>
    <script src="~/js/jqGrid/jquery.jqGrid.js"></script>
    <script src="~/js/Class.js"></script>
}