DanceStudioManager/Controllers/StudioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Security.Claims;

namespace DanceStudioManager
{
    [Authorize]
    public class StudioController : Controller
    {
        private readonly StudentsDataAccess _studentDataAccess;
        private readonly StudioDataAccess _studioDataAccess;
        private readonly InstructorDataAccess _instructorDataAccess;
        private readonly ClassDataAccess _classDataAccess;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly UserDataAccess _userDataAccess;
        private readonly AttendanceDataAccess _attendanceDataAccess;
        private readonly CalendarHelp _calendarHelp;

        public StudioController(StudentsDataAccess studentDataAccess, StudioDataAccess studioDataAccess, InstructorDataAccess instructorDataAccess,
            ClassDataAccess classDataAccess, IHttpContextAccessor httpContextAccessor, UserDataAccess userDataAccess, AttendanceDataAccess attendanceDataAccess,
            CalendarHelp calendarHelp)
        {
            _studentDataAccess = studentDataAccess;
            _studioDataAccess = studioDataAccess;
            _instructorDataAccess = instructorDataAccess;
            _classDataAccess = classDataAccess;
            _httpContextAccessor = httpContextAccessor;
            _userDataAccess = userDataAccess;
            _attendanceDataAccess = attendanceDataAccess;
            _calendarHelp = calendarHelp;
        }
        public IActionResult Dashboard()
        {
            ViewBag.text = "Dashboard";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            DashboardNeeds dashboardNeeds = new DashboardNeeds();
            var allClasses = _classDataAccess.GetAllClasses(GetCurrentStudioId());
            var allStudents = _studentDataAccess.GetAllStudents(GetCurrentStudioId());
            var allInstructors = _instructorDataAccess.GetAllInstructors(GetCurrentStudioId());

            foreach (var _class in allClasses)
            {
                var classShedule = _classDataAccess.GetClassShedule(_class.Id);
                foreach (var s in classShedule)
                {
                    if (s.Day == DateTime.Now.DayOfWeek.ToString() && _class.StartDay <= DateTime.Now)
                    {
                        _class.Hour = s.Hour;
                        dashboardNeeds.classesForToday.Add(_class);
                    }
                }
            }

            foreach (var st in allStudents)
            {
                var sL = new SelectListItem()
                {
                    Value = st.Id.ToString(),
                    Text = $"{st.Firstname} {st.Lastname}"
                };

                dashboardNeeds.AllStudents.Add(sL);
            }

            foreach (var ins in allInstructors)
            {
                var iL = new SelectListItem()
                {
                    Value = ins.Id.ToString(),
                    Text = $"{ins.Firstname} {ins.Lastname}"
                };

                dashboardNeeds.AllInstructors.Add(iL);
            }
            return View(dashboardNeeds);
        }

        [HttpPost]
        public IActionResult Dashboard(int classId)
        {
            ClassStudentVM dashboardNeeds = new ClassStudentVM();
            var instructorList = _classDataAccess.GetInstructorsConnectedToClass(classId, GetCurrentStudioId());
            var studentsIdList = _classDataAccess.GetStudentsConnectedToClass(classId, GetCurrentStudioId());
            var _class = _classDataAccess.SearchClass(classId, GetCurrentStudioId());
           
            foreach (var idsIns in instructorList)
            {
                var instructor = _instructorDataAccess.GetInstructorById(idsIns);
                dashboardNeeds.InstructorsList.Add(instructor);
            }

            foreach (var idsStu in studentsIdList)
            {
                var student = _studentDataAccess.GetStudentById(idsStu);
                dashboardNeeds.StudentsList.Add(student);
            }

            dashboardNeeds.PricePerHour = _class.PricePerHour;
            dashboardNeeds.Level = _class.Level;
            dashboardNeeds.ClassId = classId;
            var shedule  = _classDataAccess.GetClassShedule(classId);

            foreach(var s in shedule)
            {
                dashboardNeeds.SheduleDays.Add($" {s.Day} - {s.Hour} ");
            }

            return Json(dashboardNeeds);
        }

        public IActionResult Students()
        {
            ViewBag.text = "Students";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            return View();
        }

        public IActionResult GetStudents(string firstname, string lastname, string email)
        {
            List<Student> studentList = new List<Student>();
            Student student = new Student();

            if ((string.IsNullOrEmpty(firstname) || firstname == "null") 
                && (string.IsNullOrEmpty(lastname) || lastname == "null") 
                && (string.IsNullOrEmpty(email) || email == "null"))
            {
                studentList = _studentDataAccess.GetAllStudents(GetCurrentStudioId());
            }
            else
            {
                student.Firstname = firstname;
                student.Lastname = lastname;
                student.Email = email;
                studentList = _studentDataAccess.SearchStudents(student);
            }

            return Json(studentList);
        }

        public IActionResult AddNewStudent(Student student)
        {
            int studioId = GetCurrentStudioId();

            student.DateOfBirth = DateTime.ParseExact(student.DateOfBirthToString, "MM/dd/yyyy", CultureInfo.InvariantCulture);

            _studentDataAccess.AddNewStudent(student, studioId);
            return RedirectToAction("Students");
        }

        public void EditStudent(Student student)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _studentDataAccess.UpdateStudent(student, userId);
        }

        /// <summary>
        /// Students page.
        /// </summary>
        /// <param name="student"></param>
        public void DeleteStudent(Student student)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _studentDataAccess.DeleteStudent(student, userId);
        }

        /// <summary>
        /// Edit class modal.
        /// </summary>
        /// <param name="id"></param>
        [HttpPost]
        public void DeleteStudentFromClass(int id, int classid)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _studentDataAccess.DeleteStudentFromClass(id, classid, userId);
        }

        public IActionResult Instructor()
        {
            ViewBag.text = "Instructors";
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(GetCurrentStudioId()).Name;
            return View();
        }

        public IActionResult GetInstructor(string firstname, string lastname, string email)
        {
            List<Instructor> instructorList = new List<Instructor>();
            Instructor instructor = new Instructor();

            if ((string.IsNullOrEmpty(firstname) || firstname == "null")
                && (string.IsNullOrEmpty(lastname) || lastname == "null")
                && (string.IsNullOrEmpty(email) || email == "null"))
            {
                instructorList = _instructorDataAccess.GetAllInstructors(GetCurrentStudioId());
            }
            else
            {
                instructor.Firstname = firstname;
                instructor.Lastname = lastname;
                instructor.Email = email;
                instructorList = _instructorDataAccess.SearchInstructors(instructor);
            }

            return Json(instructorList);
        }

        public IActionResult AddNewInstructor(Instructor instructor)
        {
            instructor.DateOfBirth = DateTime.ParseExact(instructor.DateOfBirthToString, "MM/dd/yyyy", CultureInfo.InvariantCulture);

            int studioId = GetCurrentStudioId();
            _instructorDataAccess.AddNewInstructor(instructor, studioId);
            return RedirectToAction("Instructor");
        }

        public void EditInstructor(Instructor instructor)
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);

            _instructorDataAccess.UpdateInstructor(instructor, userId);
        }
        
        /// <summary>
        /// Instructor page.
        /// </summary>
        /// <param name="instructor"></param>
        public void DeleteInstructor(Instructor instructor)
        {

DanceStudioManager/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Web;

namespace DanceStudioManager
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserDataAccess _userDataAccess;
        private readonly StudioDataAccess _studioDataAccess;
        private readonly StudentsDataAccess _studentDataAccess;
        private readonly ClassDataAccess _classDataAccess;
        private readonly InstructorDataAccess _instructorDataAccess;
        private readonly IHostingEnvironment _appEnvironment;

        public UserController(UserDataAccess userDataAccess, StudioDataAccess studioDataAccess, StudentsDataAccess studentDataAccess, ClassDataAccess classDataAccess,
            InstructorDataAccess instructorDataAccess, IHostingEnvironment appEnvironment)
        {
            _userDataAccess = userDataAccess;
            _studioDataAccess = studioDataAccess;
            _studentDataAccess = studentDataAccess;
            _classDataAccess = classDataAccess;
            _instructorDataAccess = instructorDataAccess;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            ViewBag.text = "User profile";
            var user = GetCurrentUser();
            ViewBag.StudioName = _studioDataAccess.GetStudioInfo(user.StudioId).Name;
            var studio = _studioDataAccess.GetStudioInfo(user.StudioId);

            user.StudioName = studio.Name;
            user.PhotoUrl = studio.Photo_url;
            user.NumberOfStudents = _studentDataAccess.GetAllStudents(studio.Id).Count();
            user.NumberOfClasses = _classDataAccess.GetAllClasses(studio.Id).Count();
            user.NumberOfInstructors = _instructorDataAccess.GetAllInstructors(studio.Id).Count();

            return View("Views/Studio/User.cshtml",user);
        }

        public IActionResult Edit(User user)
        {
            var userId = GetCurrentUser().Id;
            var studio = new Studio();

            user.Id = userId;
            user.ConfirmAccount = true;
            studio.Name = user.StudioName;

            _userDataAccess.UpdateUser(user);

            var studioId = _userDataAccess.GetUserById(userId).StudioId;

            _studioDataAccess.UpdateStudio(studio, studioId);

            return RedirectToAction("Index");
        }

        public IActionResult Delete()
        {
            int userId = GetCurrentUser().Id;
            _userDataAccess.DeleteUser(userId);
            return RedirectToAction("LogOut", "Account");
        }

        [HttpPost]
        public IActionResult ChangePhoto(IFormFile PhotoUrl)
        {
            if (PhotoUrl != null)
            {

                // File to be deleted    
                string authorsFile = PhotoUrl.FileName;
                string rootFolder = Path.Combine(_appEnvironment.WebRootPath, "images", Path.GetFileName(PhotoUrl.FileName));

                try
                {
                    // Check if file exists with its full path    
                    if (System.IO.File.Exists(rootFolder))
                    {
                        // If file found, delete it    
                        System.IO.File.Delete(rootFolder);
                    }
                }
                catch (IOException ioExp)
                {
                    ModelState.AddModelError(ioExp.Message, "");
                    return RedirectToAction("Index");
                }

                var studio = new Studio();
                if (PhotoUrl != null)
                {
                    PhotoUrl.CopyTo(new FileStream(rootFolder, FileMode.Create));

                    var lastPart = rootFolder.Substring(rootFolder.IndexOf("images") - 1);
                    studio.Photo_url = lastPart;
                    _studioDataAccess.UpdateStudio(studio, GetCurrentUser().StudioId);
                }
            }
            return RedirectToAction("Index");

        }

        private User GetCurrentUser()
        {
            ClaimsPrincipal currentUser = User;
            var claims = currentUser.Claims;
            var userEmail = "";
            foreach (var c in claims) userEmail = c.Value;
            var newUser = new User();
            newUser.Email = userEmail;
            var userId = _userDataAccess.GetUserId(newUser);
            var user = _userDataAccess.GetUserById(userId);

            return user;
        }
    }
}

DanceStudioManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - DanceStudioManager</title>

    <environment include="Development">
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar  navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DanceStudioManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - DanceStudioManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

DanceStudioManager/Views/Shared/_LayoutStudio.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>
        DanceStudioManager
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- CSS Files -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/now-ui-dashboard.css?v=1.3.0" rel="stylesheet" />
</head>
<body>
    <div class="wrapper ">
        <div class="sidebar" data-color="orange">
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
            -->
            <div class="logo">
                <a class="simple-text logo-normal">
                    @ViewBag.StudioName
                </a>
            </div>
            <div class="sidebar-wrapper" id="sidebar-wrapper">
                <ul class="nav">
                    <li>
                        <a asp-controller="Studio" asp-action="Dashboard">
                            <i class="now-ui-icons design_app"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Studio" asp-action="Students">
                            <i class="now-ui-icons education_hat"></i>
                            <p>Students</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Studio" asp-action="Instructor">
                            <i class="now-ui-icons education_atom"></i>
                            <p>Instructors</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Studio" asp-action="Classes">
                            <i class="now-ui-icons ui-1_bell-53"></i>
                            <p>Classes</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Calendar" asp-action="Index">
                            <i class="now-ui-icons ui-1_calendar-60"></i>
                            <p>Calendar</p>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="reportsDropdownMenuLink" data-toggle="dropdown" aria-expanded="false">
                            <i class="now-ui-icons text_caps-small"></i>
                            Reports
                        </a>
                        <div class="dropdown-menu ml-2" aria-labelledby="reportsDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="Reports" asp-action="ClassStudent">Check class-students report</a>
                            <a class="dropdown-item" asp-controller="Reports" asp-action="Profit">Check profit reports</a>
                        </div>
                    </li>
                    <li>
                        <a asp-controller="User" asp-action="index">
                            <i class="now-ui-icons users_single-02"></i>
                            <p>User Profile</p>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
        <div class="main-panel" id="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        @if (ViewBag.text == "Students")
                        {
                            <a class="navbar-brand">Students</a>
                        }
                        @if (ViewBag.text == "Instructors")
                        {
                            <a class="navbar-brand">Instructors</a>
                        }
                        @if (ViewBag.text == "Classes")
                        {
                            <a class="navbar-brand">Classes</a>
                        }
                        @if (ViewBag.text == "Events")
                        {
                            <a class="navbar-brand">Events</a>
                        }
                        @if (ViewBag.text == "Dashboard")
                        {
                            <a class="navbar-brand">Dashboard</a>
                        }
                        @if (ViewBag.text == "User profile")
                        {
                            <a class="navbar-brand">User profile</a>
                        }
                        @if (ViewBag.text == "Reports")
                        {
                            <a class="navbar-brand">Reports</a>
                        }
                        @if (ViewBag.text == "Calendar")
                        {
                            <a class="navbar-brand">Calendar</a>
                        }
                        @if (ViewBag.text == "Class-Student report")
                        {
                            <a class="navbar-brand">Class-Student report</a>
                        }
                        @if (ViewBag.text == "Profit report")
                        {
                            <a class="navbar-brand">Profit report</a>
                        }
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <form>
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <i class="now-ui-icons ui-1_zoom-bold"></i>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="User" asp-action="Index">
                                    <i class="now-ui-icons users_single-02"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Account</span>
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="panel-header panel-header-sm">
            </div>
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="~/assets/js/core/jquery.min.js"></script>
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/js/site.js"></script>
    <!-- Chart JS -->
    <script src="~/assets/js/plugins/chartjs.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="~/assets/js/plugins/bootstrap-notify.js"></script>
    <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="../assets/js/now-ui-dashboard.min.js?v=1.3.0" type="text/javascript"></script>
    <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
    <script src="~/assets/demo/demo.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script>
        $(document).ready(function () {
            // Javascript method's body can be found in assets/js/demos.js
            demo.initDashboardPageCharts();

        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>